### ISSUE TITLE
Run docker image as non-root user

### ISSUE THREAD

**Issue by dgershman** [reconmap/web-client#100]
**Is your feature request related to a problem? Please describe.**
Currently, there isn't a great way to use the Docker image as a non-root user (which is required in some situations).

**Describe the solution you'd like**
Always run the container as non-root, if possible.

**Describe alternatives you've considered**
Basing off the existing image and then making modifications, however, this requires maintainenance.

**Additional context**
N/A

**Comment by santiagolizardo** [comment]
That has now been changed. The new default port for the web-client is `5500`. Thanks!

**Comment by dgershman** [comment]
Thanks, will test it out.
