### ISSUE TITLE
Command combo box does not show all commands

### ISSUE THREAD

**Issue by R00GLE** [reconmap/web-client#143]
When adding new Tasks the Command combo box does not show all the commands but a list of 21 items maximum.

Optionally it would be really nice if the command selection combo box had a search function to be able to search through large lists of commands.

**Comment by santiagolizardo** [comment]
Hi @R00GLE ! Thanks for reporting this.

It has been solved like this:

![image](https://user-images.githubusercontent.com/220190/162843542-a4bf80c3-a018-4984-91c9-1c8ed85d3555.png)

Essentially a drop down where you can type anything until finding your desired command.
