### ISSUE TITLE
Missing next page button

### ISSUE THREAD

**Issue by R00GLE** [reconmap/web-client#145]
When there are a large number of commands in the command list only a limited selection is shown and there is no way to page through the list of stored commands.

**Comment by santiagolizardo** [comment]
Hi @R00GLE ! Thanks for reporting this. This was already on my to-do list and today I finally managed to complete it.

![image](https://user-images.githubusercontent.com/220190/162641738-b856f2fb-9e90-4da0-a149-7a56aceae1a7.png)

**Comment by santiagolizardo** [comment]
Closing this ticket for now. Feel free to re-open if something is missing. Thanks!
