### ISSUE TITLE
Document editor same font color as background

### ISSUE THREAD

**Issue by R00GLE** [reconmap/web-client#146]
When adding a new document the WYSIWYG editor uses a white font with a white background thus it looks like there is no text. 

![image](https://user-images.githubusercontent.com/18434368/163685153-094b633e-7499-405a-bd51-503c4f47ab83.png)

with highlighted text 
![image](https://user-images.githubusercontent.com/18434368/163685177-ee95ba40-4b07-497b-8478-9470b062d78c.png)

**Comment by santiagolizardo** [comment]
Hi @R00GLE ; Thanks for reporting this issue. Unfortunately I am unable to reproduce it using dark or light themes. Could you tell me more about your setup? eg Browser, OS
Thanks!
