### ISSUE TITLE
Stylise key strokes as keyboard keys

### ISSUE THREAD

**Issue by santiagolizardo** [Reconmap/web-client#56]
Similar to 
![image](https://user-images.githubusercontent.com/220190/102940268-d93fdb00-44a7-11eb-86b2-38f0f1b435d2.png)

**Comment by pablolizardo** [comment]
ok! fixed with commit https://github.com/Reconmap/web-client/commit/cc55c06a2d3624165873fa9fee4d5d1860b7a1ca
also added subtle animation to the popup
