### ISSUE TITLE
Deploying web client under subdirectory

### ISSUE THREAD

**Issue by PauloASilva** [Reconmap/web-client#68]
Hi,
Am I the only one having troubles deploying web client under a subdirectory e.g. `http://somehost.com/reconmap`?
I am using the official docker image `quay.io/reconmap/web-client:master`, behind a reverse proxy.

In the `index.html` file there are several `%PUBLIC_URL%`, but then [the style sheet `sytle.css` doesn't have it][1].
[Reconmap logo URI is `/logo.svg`][2] and [routes are mounted on `/`][3].

I didn't find any convenient solution without changing the source code.
Do you have any suggestions?

Cheers,
Paulo A. Silva

[1]: https://github.com/Reconmap/web-client/blob/b8f06c969535b5c6637eda06e785c8b497d11700/public/index.html#L16
[2]: https://github.com/Reconmap/web-client/blob/1737a742f1d88315d9f37ec2b8bf91d93d9ebd57/src/components/layout/Header.js#L23
[3]: https://github.com/Reconmap/web-client/blob/b8f06c969535b5c6637eda06e785c8b497d11700/src/App.js#L40

**Comment by santiagolizardo** [comment]
Hi @PauloASilva ; Thanks for reporting this. This is the first time we see this requirement which means we are not fully prepared to resolve the issue.

One thing I have done is to remove the LINK to the relative CSS file (https://github.com/Reconmap/web-client/commit/912933ba846bfc5f2eb7de67cb7a034e8938d0b8) as it was not really needed.

I am reading about how to make this work and everything suggests that you either build the image yourself changing the package.json to include a homepage attribute as suggested here: https://create-react-app.dev/docs/deployment/#building-for-relative-paths or you do some rewrite magic on your webserver.

In any case, I'll continue my research and I'll get back to you with any more findings.

Thanks!

**Comment by PauloASilva** [comment]
Hi @santiagolizardo,
Thanks for reaching out.

I've already tried the rewrite approach but it doesn't work: since most of the app is rendered client-side the reverse proxy won't be able to do it (e.g. `/logo.svg` or any of the application routes).

I've done some research and found some interesting tutorial on how to do it in REACT: either using `<base url="">` with relative paths (e.g. `./logo.svg`) or a base URL/path with React Router (dynamically, based on `window.location` or statically based on a configuration variable/property).

A similar issue, related with the service worker, seems to have been reeady addressed. The same approach can be used. What do you think?

Tomorrow I'll be able to further investigate and I'll be more than happy to open a Pull Request.

Cheers,
Paulo A. Silva

**Comment by PauloASilva** [comment]
Hi @santiagolizardo,
Can you please have a look at [linked Pull Request][1]?

Some changes are still required in the `index.html` file, but I am not sure how the `%PUBLIC_URL%` works.
One way to do it is just removing the `%PUBLIC_URL%`, but I am not sure whether this will break something else.

Cheers,
Paulo A. Silva

[1]: https://github.com/Reconmap/web-client/pull/69

**Comment by PauloASilva** [comment]
According to the available documentation `%PUBLIC_URL%` is replaced at build time if an environment variable with the same name is provided. It doesn't seem to be the case, since no prefixes are added in the generated `index.html`.

Apart from configuration files `%PUBLIC_URL%` is only used in the source `index.html` file.

I think this won't be an issue and the PR shouldn't break the web client.

Cheers,
Paulo A. Silva
